version: "3.7"

services:
  authentication:
    container_name: app-authentication
    image: authentication
    build:
      context: .
      dockerfile: .docker/Dockerfile
    depends_on:
      - postgres-db
    ports:
      - "8080:8080"
      - "5005:5005"
    environment:
      SERVER_PORT: 8080
      LOG_LEVEL_APP: INFO
      POSTGRES_USERNAME: root
      POSTGRES_PASSWORD: example
      POSTGRES_PORT: 5432
      POSTGRES_URL: jdbc:postgresql://postgres-db:5432/authentication
    networks:
      - authentication-network

  postgres-db:
    image: postgres
    container_name: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=example
      - POSTGRES_DB=authentication
    ports:
      - "5432:5432"
    networks:
      - authentication-network
  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - "7070:8080"
    networks:
      - authentication-network

networks:
  authentication-network: